apiVersion: v1
kind: Service

metadata:
  name: nginx
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing

spec:
  type: LoadBalancer

  selector:
    app: nginx
    version: green

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80