apiVersion: v1
kind: Service

metadata:
  name: nginx

spec:
  type: LoadBalancer

  # Service uses these labels to select Pods
  selector:
    app: nginx
    version: blue

  ports:
    - protocol: TCP
      port: 80        # Service port
      targetPort: 80  # Container port